{% set name = "snakeviz" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jiffyclub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c7432fbcad585f451ace93d02cc89e6e2d22f0b0aa75c5f9109cd3c231e81336

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - snakeviz = snakeviz.cli:main
  number: 0

requirements:
  build:
    - pip
    - python
    - setuptools
    - tornado >=2.0
  run:
    - python
    - tornado >=2.0

test:
  commands:
    - snakeviz -h
  imports:
    - snakeviz

about:
  home: https://jiffyclub.github.io/snakeviz/
  license: BSD 3-Clause
  summary: An in-browser Python profile viewer
  description: |
    SnakeViz is a viewer for Python profiling data that runs as a web application in your browser.
  doc_url: https://jiffyclub.github.io/snakeviz
  dev_url: https://github.com/jiffyclub/snakeviz

extra:
  recipe-maintainers:
    - gforsyth
