travis:
  secure:
    BINSTAR_TOKEN: PuBJfjWT0F3inFeHdUh86V3q+0rlrIFcf7vcImcAW1jkW9WcEMGKMDOcp57y9Hj5/RYd/lmvV3QWqfNqZNVJOZ2nL9uQ1MvfDbpZ+ihYNm+KtQleJaODUWp+BUR0EaLokDgNJcbuQCnmCvU5HuPLWdHkEjEqhTKtmDX52VZqi8GRoAuzTCU6HIAIDGJU5dV1DUJ3XjBC/jCMCi1aUlEDzVAVRXgfmU9FPNuHP5P9SQ5F6Mb04n9vavHWw/HrxJJTcAvGhpUA/WbTw59843+ZlIznvjuQ635awE7yz3Ndi4x/c1z4INiiQE8lUGblbgZVSYU+CWbWXRdUca75tgOrbmXN4B0NtMJDaaaSOB5lWprqWID/G5OwaKAEuYhJnIHUn3Zvn+QhDT2k4VEuW3jOQ8yWOkoG0u0YvQznveQ1M0KcC1+Tru8iNnhiJjpvRK1zi9W+hAy15gL4B2gFUWXUv5NK9LnpUJ0rEtRM545OECIp+eK38keniKj1c6hPCdd0DTKgpoqMBn+6979mxhdp6GCoCs3oNjNb/NK/8D93j6qWElM7e5DAqlcLt2x18EwZjYgp0N/htOYCNsUm77EfpofmJwHoF/N3REqnfJWGoxmhT1zT31TrryZ4BABMQVMpRnB5gYPf5o/oZxFbNNg/U7ch07kk8CKX1vZIVRUcZh4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
